name: CMake

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc]
        include:
          - os: windows-latest
            compiler: cl

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -G"Unix Makefiles" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      if: "!(contains( matrix.os, 'windows') && contains( matrix.compiler, 'cl'))"
      
    - name: Configure CMake (MSVC)
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -G"Visual Studio 17 2022" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      if: "contains( matrix.os, 'windows') && contains( matrix.compiler, 'cl')"

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
